"REPOSITORIO 2"
"LO INTENTADO CASI TODO PARA CONVENCERTE"
"Mientras el mundo se derrumba aqui a mis pies"
"Mientras aprendo de esta soledad que desconozcoooo"
"Me vuelvo a preguntar quizas si sobrevivireee"